In [15]:
import pandas as pd
# from matplotlib import pyplot as plt
import numpy as np
import scipy

In [6]:
columns = [
    "timestamp", "open", "high", "low", "close", "volume",
    "close_time", "quote_asset_volume", "trade_count",
    "taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", "ignore"
]


In [8]:
vvv = pd.read_json('VVVUSDT.json' )
vvv.columns = columns
vvv.head()

timestamp    open    high    low  close      volume     close_time  \
0  1738137600000  10.636  10.900  9.609  9.893   883986.28  1738141199999   
1  1738141200000   9.891  10.478  9.437  9.655  1292366.81  1738144799999   
2  1738144800000   9.656   9.858  9.100  9.759  1153439.80  1738148399999   
3  1738148400000   9.759   9.857  9.283  9.640   658070.18  1738151999999   
4  1738152000000   9.640  10.250  9.419  9.707  1109459.60  1738155599999   

   quote_asset_volume  trade_count  taker_buy_base_asset_volume  \
0        8.947995e+06        38337                    460685.34   
1        1.284237e+07        63219                    661437.90   
2        1.100424e+07        69597                    572467.40   
3        6.307598e+06        50421                    337679.30   
4        1.088006e+07        74921                    570164.03   

   taker_buy_quote_asset_volume  ignore  
0                  4.661827e+06       0  
1                  6.573672e+06       0  
2                  5.469683e+06       0  
3                  3.236772e+06       0  
4                  5.594300e+06       0

In [31]:
ohlc = vvv[['open', 'high', 'low', 'close']].to_numpy()

# **Tugas Praktikum**

Nomor 1: Buatlah matriks 3×3 dengan elemen berupa bilangan berurutan dari 1 hingga 9. Cetak hasilnya.

In [16]:
matrix_1_9 = np.array([i for i in range(1,10)]).reshape(3,3)
matrix_1_9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Nomor 2

In [17]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print (A+B)

[[ 6  8]
 [10 12]]


Nomor 3

In [21]:
C = np.eye(2, dtype=np.int8)
D = np.array([[2,3], [4,5]])
np.dot(C,D)

array([[2, 3],
       [4, 5]])

Nomor 4

In [22]:
E = np.array([[1,2,3], [4,5,6]])
E.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

Nomor 5

In [23]:
A = np.array([[1,2], [3,4]])
B = np.array([[10], [24]])
np.linalg.solve(A, B)

array([[4.],
       [3.]])

Nomor 6

In [28]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6], [7,8]])

print("Hstack: ", np.hstack([A,B]), sep='\n')
print("Vstack: ", np.vstack([A,B]), sep='\n')

Hstack: 
[[1 2 5 6]
 [3 4 7 8]]
Vstack: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Nomor 7

In [29]:
X = np.array([1,2,3,4,5,6])
print("2x3: \n", X.reshape(2,3))
print("3x2: \n", X.reshape(3,2))

2x3: 
 [[1 2 3]
 [4 5 6]]
3x2: 
 [[1 2]
 [3 4]
 [5 6]]


array([[1., 2.],
       [3., 4.]])