# **I love SCPK**
```
pip install numpy
```
>test

In [2]:
import numpy as np

In [27]:
x = 10
input("test: ")

'test'

In [34]:
np.array([i for i in range(1,10)]).reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
A + B

array([[ 6,  8],
       [10, 12]])

In [42]:
C = np.array([[1,0],[0,1]])
D = np.array([[2,3], [4,5]])
np.dot(C,D)

array([[2, 3],
       [4, 5]])

In [37]:
E = np.array([[1,2,3], [4,5,6]])
np.transpose(E)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [10],
    [24],
])

np.dot(np.linalg.inv(A), B)

array([[4.],
       [3.]])